# Generated by Django 2.1.2 on 2018-10-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='button_status',
            new_name='button',
        ),
    ]
